### ISSUE TITLE
Make client able to cope with small schema change

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#225]
Recently, the `hash` field went from an array to a single-valued field.  The client currently breaks because of this:

```
access_ukwa-ui.1.ms862gz4ppzs@access    | com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
access_ukwa-ui.1.ms862gz4ppzs@access    |  at [Source: java.io.StringReader@71a815b1; line: 1, column: 144138] (through reference chain: com.marsspiders.ukwa.solr.data.SolrSearchResult["response"]->com.marsspiders.ukwa.solr.data.ResponseBody["docs"]->java.util.ArrayList[21]->com.marsspiders.ukwa.solr.data.ContentInfo["hash"])
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:260) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:187) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:177) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:20) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.marsspiders.ukwa.solr.SolrCommunicator.sendRequest(SolrCommunicator.java:89) ~[classes!/:1.4.7.RELEASE]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.marsspiders.ukwa.solr.SolrSearchService.sendRequest(SolrSearchService.java:220) [classes!/:1.4.7.RELEASE]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.marsspiders.ukwa.solr.SolrSearchService.searchContent(SolrSearchService.java:164) [classes!/:1.4.7.RELEASE]
access_ukwa-ui.1.ms862gz4ppzs@access    |       at com.marsspiders.ukwa.controllers.SearchController.searchPage(SearchController.java:178) [classes!/:1.4.7.RELEASE]
```

However, as far as I know, the UI should not use this field at all, so it should be dropped. Then the client will be able to run across all collections.  @GilHoggarth can help set up beta to test this.

**Comment by anjackson** [comment]
Pretty sure we just need to delete this:

https://github.com/ukwa/ukwa-ui/blob/e138e4641462a3df79383fe7e55060bb2dd320dd/src/main/java/com/marsspiders/ukwa/solr/data/ContentInfo.java#L37-L38

**Comment by anjackson** [comment]
Oops messed up the link but c58f79202729583181075db3a4f2f4b6560b5a4a and 5faa9b05fde2590fda854022300f7f6a6ec9a89f should resolve this.

**Comment by anjackson** [comment]
Verified as working on BETA.
