### ISSUE TITLE
Error on some results sets

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#228]
Some searches, likely ones with lots of hits, are erroring:

```
access_ukwa-ui-beta.1.uny3jpgwod5v@access    | 2019-03-06 15:09:16.992 ERROR 1 --- [nio-8080-exec-7] c.m.ukwa.solr.SolrCommunicator           : Failed to get data from Solr
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |
access_ukwa-ui-beta.1.uny3jpgwod5v@access    | com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2793657774) out of range of int
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at [Source: java.io.StringReader@6a768afe; line: 1, column: 561]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at [Source: java.io.StringReader@6a768afe; line: 1, column: 551] (through reference chain: com.marsspiders.ukwa.solr.data.SolrSearchResult["response"]->com.marsspiders.ukwa.solr.data.ResponseBody["numFound"])
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1600) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.marsspiders.ukwa.solr.SolrCommunicator.sendRequest(SolrCommunicator.java:89) ~[classes!/:1.4.7.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.marsspiders.ukwa.solr.SolrSearchService.sendRequest(SolrSearchService.java:220) [classes!/:1.4.7.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.marsspiders.ukwa.solr.SolrSearchService.searchContent(SolrSearchService.java:164) [classes!/:1.4.7.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.marsspiders.ukwa.controllers.SearchController.searchPage(SearchController.java:174) [classes!/:1.4.7.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.marsspiders.ukwa.LocaleConfiguration$LocaleResolverFilter.doFilterInternal(LocaleConfiguration.java:80) [classes!/:1.4.7.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar!/:8.5.15]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    | Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2793657774) out of range of int
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at [Source: java.io.StringReader@6a768afe; line: 1, column: 561]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928) ~[jackson-core-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866) ~[jackson-core-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694) ~[jackson-core-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:299) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:279) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.8.jar!/:2.8.8]
access_ukwa-ui-beta.1.uny3jpgwod5v@access    |  ... 89 common frames omitted
```

It seems we have `int` fields in e.g. ResponseBody where we should have `long`.

**Comment by anjackson** [comment]
Ah, woah, this is unresolved?! oh dear.

**Comment by anjackson** [comment]
Looks like it's just 

https://github.com/ukwa/ukwa-ui/blob/e138e4641462a3df79383fe7e55060bb2dd320dd/src/main/java/com/marsspiders/ukwa/solr/data/ResponseBody.java#L14

**Comment by anjackson** [comment]
Verified as working. Going to release this.
